# Generated by Django 5.0 on 2023-12-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('texte', models.TextField()),
                ('question', models.CharField(max_length=150)),
                ('reponse', models.CharField(max_length=150)),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LectureRapide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('texte', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MathsCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MathsCompter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('liste', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orthographe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('liste', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('résultat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mdp', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school_level',
            field=models.CharField(choices=[('CP', 'cp'), ('CE1', 'ce1'), ('CE2', 'ce2'), ('CM1', 'cm1'), ('CM2', 'cm2')], max_length=20),
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dys_app.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_option', models.CharField(max_length=255)),
                ('est_correcte', models.BooleanField(default=False)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dys_app.phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_correcte', models.BooleanField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dys_app.exercice')),
                ('option_selectionnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dys_app.option')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dys_app.phrase')),
            ],
        ),
    ]
