# Generated by Django 5.0 on 2023-12-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0003_enfant_exercice_lecture_lecturerapide_mathscalcul_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Parent',
        ),
    ]
