# Generated by Django 5.0 on 2023-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0004_rename_user_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfant',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mdp',
            field=models.CharField(default='@', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(default='test@test.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(default='prenomTest', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('parent', 'parent'), ('Enfant', 'enfant')], default='parent', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
