# Generated by Django 4.2.7 on 2023-12-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0010_exercisetheme_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetheme',
            name='image_url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
