# Generated by Django 4.2.7 on 2023-12-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0011_exercisetheme_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetheme',
            name='image_url',
        ),
    ]
